apiVersion: v1
kind: Pod
metadata:
  name: my-pod-cka
  labels:
    app: my-pod-cka
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
      - mountPath: "/var/www/html"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: my-pvc-cka
  dnsPolicy: ClusterFirst
  restartPolicy: Always