apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
spec:
  containers:
    - name: redis-container
      image: redis:latest
      resources:
        requests:
          memory: "5Mi"
          cpu: "15m"
        limits:
          memory: "10Mi"
          cpu: "100m"