apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv-cka
spec:
  storageClassName: standard
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"
    type: DirectoryOrCreate