apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rc
  labels:
    app: myapp-rc
    type: front-end
spec:
  replicas: 3

  template:
    metadata:
      name: myapp-rc
      labels:
        app: myapp-rc
        type: front-end
    spec:
      containers:
        - name: nginx
          image: nginx
  selector:
    matchLabels:
        type: myapp-rc