apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: strict-prod-policy
  namespace: prod
spec:
  podSelector: {}

  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:

        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: frontend
          podSelector:
            matchLabels:
              role: web
      ports:
        - protocol: TCP
          port: 8080      


  egress:
    - to:
        - namespaceSelector: {} 
      ports:
        - protocol: UDP
          port: 53

    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: database
          podSelector:
            matchLabels:
              role: db
      ports:
        - protocol: TCP
          port: 5432       
