apiVersion: v1
kind: Service
metadata:
  name: multi-port-service
  namespace: default
spec:
  selector:
    app: my-app
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP

    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP

    - name: metrics
      port: 9100
      targetPort: 9100
      protocol: TCP
