apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-app
  namespace: default
  labels:
    app: video-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: video-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: video-app
    spec:
      containers:
      - name: video-app
        image: your-registry/video-app:latest  # Replace with your actual video app image
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Always