apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cache
  name: cache-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cache-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 30%
      maxSurge: 45%
  template:
    metadata:
      labels:
        app: cache-deployment
    spec:
      containers:
      - image: redis:7.0.13
        name: redis