apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrc2
spec:
  replicas: 2
  selector: 
    matchExpressions:
    - { key: dc , operator: In,values: [ IN ] }



  template:
    metadata:
      name: "mypod"
      labels:
        dc: IN
    spec:
      containers:
        - name: "myrc1"
          image: "httpd"
