apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: test-container
    image: busybox
    command: [ "sleep", "3600" ]
    volumeMounts:
    - name: secret-volume
      mountPath: "/etc/creds"
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: mysecret
