apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc1
spec:
  replicas: 2
  selector: 
    dc: IN
  template:
    metadata:
      name: "mypod"
      labels:
        dc: IN
    spec:
      containers:
        - name: "myrc1"
          image: "httpd"
